export const chartTimeRanges = [
  { label: '1D', value: '1days' },
  { label: '7D', value: '7days' },
  { label: '1M', value: '1months' },
  { label: '3M', value: '3months' },
  { label: '6M', value: '6months' },
];

export const dogecoinCalculatorFaqs = [
  {
    question: "How to use the Dogecoin mining calculator?",
    answer: [
      "Every aspect of our Dogecoin mining calculator has been developed for miners by miners.",
      "The latest version of the Dogecoin mining calculator makes it simple and easy to quickly calculate Dogecoin mining profits by adjusting the mining hashrate values or by selecting one of the Dogecoin mining hardware devices from the Dogecoin miners list.",
      "The Dogecoin mining information is updated continually with the current block mining information. This information is used as the default inputs for the DOGE mining calculator along with the default hashrate and wattage specs from the best Dogecoin miner.",
      "With this information and our backend hashrate calculator, you can calculate your DOGE mining profits - providing valuable and strategic profitability information allowing you as the miner to make better informed decisions about Dogecoin mining.",
      "Along with the Dogecoin mining profitability, the list of top 5 Dogecoin miners is updated frequently. A Dogecoin miner is also referred to as a Dogecoin mining rig, or a Dogecoin mining hardware device, or a Dogecoin mining machine, but we simply call them miners, or more specifically, Dogecoin miners.",
      "Each DOGE mining calculator input has been preloaded with the best Dogecoin mining hardware hashrate and energy consumption in watts, average electricity costs as well as the current Dogecoin price, Dogecoin block reward, and Dogecoin difficulty.",
      "Calculate your Dogecoin mining profitability and estimated mining rewards by starting with the Dogecoin mining hashrate calculator inputs above; mining hardware, mining costs, and mining reward.",
    ],
  },
  {
    question: "Is Dogecoin mining still profitable?",
    answer: [
      "Yes, mining Dogecoin is still profitable - based on the mining hardware hashrate of 17,000.00 MH/s, electricity costs, and pool / maintenance fees provided.",
      "While, mining Dogecoin is still profitable as of right now...",
      "Mining profitability can change very quickly.",
      "The blockchain is constantly growing and the Dogecoin difficulty increases and decreases over time based on the total computing power currently mining blocks and generating hashes.",
      "That said, we recommend checking your mining profitability frequently.",
      "The Dogecoin mining profitability results and mining rewards were calculated using the best DOGE mining calculator with the following inputs.",
      "A DOGE mining difficulty of 47,710,000.00, a DOGE mining hashrate of 17,000.00 MH/s consuming 3,450 watts of power at $0.10 per kWh, and a block reward of 10,000.00 DOGE at $0.1609 (DOGE to USD).",
    ],
  },
  {
    question: "How many Dogecoin can you mine a day?",
    answer: [
      "Based the mining hardware inputs provided, 67.21 Dogecoin can be mined per day with a Dogecoin mining hashrate of 17,000.00 MH/s, a block reward of 10000 DOGE, and a Dogecoin difficulty of 47,710,000.00.",
      "After deducting mining power costs and mining fees, the final daily Dogecoin mining profit is $2.59 Dogecoin to USD.",
    ],
  },
  {
    question: "How long does it take to mine 1 Dogecoin?",
    answer: [
      "As of Saturday, November 15, 2025, it would take 0.015 days to mine 1 Dogecoin at the current Dogecoin difficulty level along with the mining hashrate and block reward; a Dogecoin mining hashrate of 17,000.00 MH/s consuming 3,450.00 watts of power at $0.10 per kWh, and a block reward of 10000 DOGE.",
      "It is important to point out that the number of days calculated does not account for difficulty increases and decrease as well as block reward increases and decrease (halvening).",
    ],
  },
  {
    question: "What are the default Dogecoin mining calculator inputs?",
    answer: [
      "Hashrate: 17,000.00 MH/s (top-tier ASIC spec)",
      "Power: 3,450 watts",
      "Electricity Cost: $0.10 per kWh",
      "Difficulty: 47,710,000.00",
      "Block Reward: 10,000 DOGE",
      "DOGE Price: $0.1609",
      "Pool/Maintenance Fee: Included in profitability model",
    ],
  },
];

export const dogecoinMiners = [
  {
    id: 1,
    manufacturer: "Bitmain",
    name: "Antminer L9 Dogecoin Miner 17G",
    hashrateValue: 17000,
    hashrateUnit: "MH/s",
    power: 3450,
    efficiency: 0.20,
    cost: 14399,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/antminer-l9-dogecoin-miner-17g.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 2,
    manufacturer: "VolcMiner",
    name: "D1 Dogecoin Miner",
    hashrateValue: 17000,
    hashrateUnit: "MH/s",
    power: 3900,
    efficiency: 0.23,
    cost: 12599,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/d1-dogecoin-miner.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 3,
    manufacturer: "Bitmain",
    name: "Antminer L9 Dogecoin Miner 16G",
    hashrateValue: 16000,
    hashrateUnit: "MH/s",
    power: 3360,
    efficiency: 0.21,
    cost: 13499,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/antminer-l9-dogecoin-miner-16g.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 4,
    manufacturer: "Bitmain",
    name: "Antminer L9 Dogecoin Miner 15G",
    hashrateValue: 15000,
    hashrateUnit: "MH/s",
    power: 3300,
    efficiency: 0.22,
    cost: 12799,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/antminer-l9-dogecoin-miner-15g.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 5,
    manufacturer: "ElphaPex",
    name: "DG1+",
    hashrateValue: 14400,
    hashrateUnit: "MH/s",
    power: 3950,
    efficiency: 0.27,
    cost: 10000,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/dg1-plus.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 6,
    manufacturer: "ElphaPex",
    name: "DG1",
    hashrateValue: 11000,
    hashrateUnit: "MH/s",
    power: 3420,
    efficiency: 0.31,
    cost: 7300,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/dg1.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 7,
    manufacturer: "Bitmain",
    name: "Antminer L7",
    hashrateValue: 9500,
    hashrateUnit: "MH/s",
    power: 3425,
    efficiency: 0.36,
    cost: 5699,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/antminer-l7.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 8,
    manufacturer: "Fluminer",
    name: "L1 Dogecoin Miner",
    hashrateValue: 5300,
    hashrateUnit: "MH/s",
    power: 1200,
    efficiency: 0.23,
    cost: 5699,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/l1-dogecoin-miner.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 9,
    manufacturer: "GoldShell",
    name: "Goldshell LT6",
    hashrateValue: 3350,
    hashrateUnit: "MH/s",
    power: 3200,
    efficiency: 0.96,
    cost: 5499,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/goldshell-lt6.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 10,
    manufacturer: "iBeLink",
    name: "BM-L3 Dogecoin Miner",
    hashrateValue: 3200,
    hashrateUnit: "MH/s",
    power: 3000,
    efficiency: 0.94,
    cost: 2199,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/bm-l3-dogecoin-miner.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 11,
    manufacturer: "GoldShell",
    name: "Goldshell LT5 Pro",
    hashrateValue: 2450,
    hashrateUnit: "MH/s",
    power: 3100,
    efficiency: 1.27,
    cost: 7999,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/goldshell-lt5-pro.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 12,
    manufacturer: "VolcMiner",
    name: "Mini Dogecoin Miner",
    hashrateValue: 2200,
    hashrateUnit: "MH/s",
    power: 500,
    efficiency: 0.23,
    cost: 1799,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/mini-dogecoin-miner.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 13,
    manufacturer: "Innosilicon",
    name: "A6+ LTC Master",
    hashrateValue: 2200,
    hashrateUnit: "MH/s",
    power: 2100,
    efficiency: 0.95,
    cost: 3000,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/a6-plus-ltc-master.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 14,
    manufacturer: "ElphaPex",
    name: "DG Home 1 Dogecoin Miner",
    hashrateValue: 2100,
    hashrateUnit: "MH/s",
    power: 630,
    efficiency: 0.30,
    cost: 2469,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/dg-home-1-dogecoin-miner.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 15,
    manufacturer: "GoldShell",
    name: "Goldshell LT5",
    hashrateValue: 2050,
    hashrateUnit: "MH/s",
    power: 2080,
    efficiency: 1.01,
    cost: 10999,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/goldshell-lt5.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 16,
    manufacturer: "GoldShell",
    name: "Goldshell LT LITE",
    hashrateValue: 1620,
    hashrateUnit: "MH/s",
    power: 1450,
    efficiency: 0.90,
    cost: 4699,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/goldshell-lt-lite.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 17,
    manufacturer: "Bitmain",
    name: "Antminer L3+",
    hashrateValue: 504,
    hashrateUnit: "MH/s",
    power: 800,
    efficiency: 1.59,
    cost: 2249,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/antminer-l3-plus.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 18,
    manufacturer: "GoldShell",
    name: "Goldshell Mini DOGE Pro",
    hashrateValue: 205,
    hashrateUnit: "MH/s",
    power: 220,
    efficiency: 1.07,
    cost: 1090,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/goldshell-mini-doge-pro.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  },
  {
    id: 19,
    manufacturer: "GoldShell",
    name: "Goldshell Mini DOGE",
    hashrateValue: 185,
    hashrateUnit: "MH/s",
    power: 233,
    efficiency: 1.26,
    cost: 1499.99,
    thumbnail: "https://www.coinwarz.com/content/v3/images/mining-hardware/goldshell-mini-doge.png",
    buyUrl: "https://www.jinglemining.com/?utm_source=COINWARZ&utm_medium=Listing&utm_campaign=MiningHardware&utm_id=COINWARZ&ref=coinwarz"
  }
];